version: "3.8"
services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: "mysql"
    volumes:
      - "./db:/var/lib/mysql"
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=brs
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
  web:
    build: .
    links:
      - mysql
    container_name: WebService
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DB_PORT=3306
      - DB_NAME=brs
      - DB_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_USER_PASSWORD=pass
    depends_on:
      - mysql